### ISSUE TITLE
Subscribe feeds folders related issues since version 2.3rc99 to 2.4.0a1

### ISSUE THREAD

**Issue by MrJustMe** [ancestorak/brief#258] opened 2017-09-12 09:03 UTC
Hi, keep good work
.- Since version 2.3rc99:
The extension creates a new 'Subscribe Feeds' folder it seems every time the addon is updated, this cause after each update you get your brief empty, current solution till now, you will have move manually your feeds from the older folder to the new one, after that, brief start updating your feeds as usual and everything is back to normallity again.
.- Version 2.4.0a1:
Exactly the same as the previous point, in addintion to that, brief create a new empty!! 'Subscribe Feeds' folder every time i restart the browser what?. ***The fix was the same, now news folders are created every time i restart the browser but feeds are ok since the new created folder in markers are empty, so i have to delete it.

OS: Windows 10 Pro 64 bits fulll updated.
Browser: Firefox 55.0.3 64 bits.

Note1: My current language is spanish, till now, the created folders was in my native language 'Canales subscritos', since this version new folder name are in english!, 'Subscribe Feeds' >> ?
Note2: Firefox have its own 'Subscribe Feeds' folder and its own way to add feeds to that place, perhaps you can use them with your addon to simplify things?.

Man, i love this addon!
Have a nice day & night there.

**Comment by tanriol** [comment] 2017-09-12 09:56
> The extension creates a new 'Subscribe Feeds' folder it seems every time the addon is updated

I've noticed the problem with new folders a few times, but haven't been able to reproduce it reliably yet. Will try to do that :-)

> Exactly the same as the previous point, in addintion to that, brief create a new empty!! 'Subscribe Feeds' folder every time i restart the browser

Does not reproduce for me :-( restarting the browser does not cause new folders to be created. Does it create a new folder every restart for you?

> My current language is spanish, till now, the created folders was in my native language 'Canales subscritos', since this version new folder name are in english!, 'Subscribe Feeds'

This is expected for development versions as the localizations are disabled for them. The Brief's UI should also be in English on development versions, isn't it?

> Firefox have its own 'Subscribe Feeds' folder and its own way to add feeds to that place, perhaps you can use them with your addon to simplify things?

Not now... actually, with Firefox 57 Brief will have to stop using bookmarks and keep the feed list in the addon itself.

**Comment by MrJustMe** [comment] 2017-09-13 00:51
> Exactly the same as the previous point, in addintion to that, brief create a new empty!! 'Subscribe  Feeds' folder every time i restart the browser

> > Does  not reproduce for me :-( restarting the browser does not cause new folders to be created. Does it create a new folder every restart for you?

I'm not really sure. Currently i think the addon is creating the new folder when it refresh the feeds, or perhaps when it is going to read my feeds and found something new. I always delete the feeds after i have read them :)
I will try to replicate something tomorrow if i can, currently i'm out of time :/
Here are an example picture: https://i.imgur.com/epeVA5Z.png

**Comment by ianjoneill** [comment] 2017-09-14 05:39
I'm seeing the same issue with Brief 2.4.0a2 on Firefox 56.0b11 (x64) on Windows.

I am in a slightly different scenario though - I have a custom home folder (set to a folder called "Feeds"), which was set up back when this was possible through the UI.

If I change the home folder back using the config preference `extensions.brief.homeFolder` and open Brief, it shows my feeds as expected. If I then close Firefox and reopen it, a new "Subscribed Feeds" folder appears in my bookmarks list, which `extensions.brief.homeFolder` now points to, leading to an empty feeds list. Changing the config preference again brings back my feed list.

Looking in the browser console, the only log line I see from brief is:
```
Brief: extension startup
```

**Comment by tanriol** [comment] 2017-09-14 08:10
Looking at the Mozilla Bugzilla, these look like the [bugs](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=ALL+getItemTitle) about `getItemTitle` spontaneously failing. That sounds rather unfortunate as this is the way Brief checks whether the `Subscribed Feeds` folder still exists. I don't have an idea right now about how to fix this problem reliably.

**Comment by MrJustMe** [comment] 2017-09-14 08:27
I'm not a programer so i have no idea, but firefox have its own way to manage feeds, [Live Bookmarks](https://support.mozilla.org/en-US/kb/live-bookmarks?redirectlocale=en-US&redirectslug=Live+Bookmarks). I wonder if it is not possible to change the **brief subcribe folder** for the **firefox subcribe folder** by default to fix the problem, maybe i'm asking for something that it is not possible, in that case, excuse that.

**Comment by thebat137** [comment] 2017-09-14 14:10
Is this perhaps related to issue #138?  Back in the day, I followed the instructions in this comment:

https://github.com/ancestorak/brief/issues/138#issuecomment-76418364

to change my Brief Subscribed Feeds folder to always be the Firefox Subscribed Feeds folder and have not had problems of this kind since.

**Comment by tanriol** [comment] 2017-09-14 19:48
Not in the next few months, old APIs will be dropped very soon, while new ones will not be available for quite some time.

**Comment by tanriol** [comment] 2017-09-17 00:09
I've tried to workaround the intermittent failures in 2b1d3de9d9fe43fa3813d50c21bf5b645477efdd. Not sure if anything else can be easily done to this problem. I hope the problem will not show up with Brief 2.4.0a3.

**Comment by ianjoneill** [comment] 2017-09-17 07:23
I've just upgraded to 2.4.0a3 and the problem seems to be resolved (for me at least).

**Comment by tanriol** [comment] 2017-09-17 07:45
@ianjoneill Nice to hear!

@MrJustMe Does it reproduce for you in 2.4.0a3?

**Comment by MrJustMe** [comment] 2017-09-17 07:50
It seems to be ok at least for the moment!.

**Comment by tanriol** [comment] 2017-09-19 07:07
Fine, closing for now, feel free to reopen if the bug comes back.

**Closed by tanriol** 2017-09-19 07:07 UTC
