### ISSUE TITLE
Refresh Hangs

### ISSUE THREAD

**Issue by davimack** [ancestorak/brief#232] opened 2017-03-31 15:33 UTC
The past few days I've had to stop and re-start the feed refresh process.  I believe it's that one of the feeds is nonresponsive, but I cannot figure out which one in particular that would be (I will attempt to do so and see if I can provide you an example).

I believe that Brief should provide the ability to configure a timeout for nonresponsive feeds.

As I'm not at all aware of the architecture I'll avoid suggesting multi-threading ... but it would be nice if it were not a linear process to update the feeds.  Something to think about.

**Comment by tanriol** [comment] 2017-03-31 15:38
Thank you for testing! I'm assuming you're working with the beta version (Brief 2.3b1), please correct me if not.

> The past few days I've had to stop and re-start the feed refresh process.

What did the problem look like? Brief not updating feeds at all?

> I believe it's that one of the feeds is nonresponsive, but I cannot figure out which one in particular that would be

If the Brief tab is open during the update, you should be able to see a spinner instead of a favicon in the feed list.

> I believe that Brief should provide the ability to configure a timeout for nonresponsive feeds.

Brief has such a timeout, although it's not configurable.

> ...it would be nice if it were not a linear process to update the feeds.

Feeds are updated in parallel actually; Brief does not start them all at once to avoid overloading Firefox, but a feed still updating should not stop the following ones from updating too.

**Comment by davimack** [comment] 2017-03-31 15:45
I'm using version 2.2.2

The problem looked like feeds not updating at all, although that's not entirely accurate: it proceeds up to a certain point and then stops.  I then go through reading things and it sits there, never finishing.

I have expanded my folders & there are no spinner icons, just the favicons I expect or the rss feed icon.

**Comment by tanriol** [comment] 2017-03-31 16:17
> it proceeds up to a certain point and then stops

So, the progress meter stops at some value and does not go to end? Yes, if Brief is stuck in this way, the next update cannot start on its own...

Does it hang every time or sometimes finish correctly?

> I have expanded my folders & there are no spinner icons, just the favicons I expect or the rss feed icon.

Note that you need the Brief tab to stay open without F5 or reopening through the update as refreshing it will replace the spinners with favicons again.

I hardly see a way this can happen and am actually *very* interested in a feed consistently causing this problem.

**Comment by tanriol** [comment] 2017-03-31 16:28
Also, could you please try the following:
- switch the Brief tab to the bookmarks view (to avoid extra messages)
- open the Firefox Browser Console (Ctrl+Shift+J)
- clear it (the button in the upper left corner)
- start update and let it hang;
- then, in a minute or two, copy the messages from the Browser Console here (including file names and line numbers on the right side).
Basically, I'm most interested in errors in `FeedUpdateService.jsm` or `Storage.jsm`

**Comment by davimack** [comment] 2017-03-31 16:32
It hangs every time, apparently - it has done for the past few days, at least.

I expanded all of my folders, stopped & restarted the synch, and then followed it down through the update process.  It appears to have hung on the following feeds:
<img width="164" alt="capture" src="https://cloud.githubusercontent.com/assets/12926523/24559792/e40e7f18-15f4-11e7-8842-f4957584e667.PNG">
These feeds are:
http://feeds.feedburner.com/HumonComics
http://feeds.feedburner.com/Lamebook
http://feeds.feedburner.com/satwcomic

I will follow your requested procedure and get back to you.

**Comment by davimack** [comment] 2017-03-31 16:38
OK, looks like it's hanging in Storage.jsm although that's just part of the stack:

A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Mar 31 2017 09:34:34 GMT-0700 (Pacific Standard Time)
Full Message: 
Full Stack: JS frame :: chrome://brief/content/brief.js :: getTopWindow :: line 421
JS frame :: chrome://brief/content/feedview.js :: FeedView_onEntriesUpdated :: line 470
JS frame :: resource://brief/Storage.jsm :: FeedProcessor_executeAndNotify :: line 910
JS frame :: resource://gre/modules/Task.jsm :: TaskImpl_run :: line 319
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 932
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 813
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 747  brief.js:421
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Mar 31 2017 09:35:15 GMT-0700 (Pacific Standard Time)
Full Message: 
Full Stack: JS frame :: chrome://brief/content/brief.js :: getTopWindow :: line 421
JS frame :: chrome://brief/content/feedview.js :: FeedView_onEntriesAdded :: line 462
JS frame :: resource://brief/Storage.jsm :: FeedProcessor_executeAndNotify :: line 894
JS frame :: resource://gre/modules/Task.jsm :: TaskImpl_run :: line 319
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 932
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 813
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 747  brief.js:421
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Mar 31 2017 09:35:43 GMT-0700 (Pacific Standard Time)
Full Message: 
Full Stack: JS frame :: chrome://brief/content/brief.js :: getTopWindow :: line 421
JS frame :: chrome://brief/content/feedview.js :: FeedView_onEntriesAdded :: line 462
JS frame :: resource://brief/Storage.jsm :: FeedProcessor_executeAndNotify :: line 894
JS frame :: resource://gre/modules/Task.jsm :: TaskImpl_run :: line 319
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 932
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 813
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 747  brief.js:421
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Mar 31 2017 09:35:58 GMT-0700 (Pacific Standard Time)
Full Message: 
Full Stack: JS frame :: chrome://brief/content/brief.js :: getTopWindow :: line 421
JS frame :: chrome://brief/content/feedview.js :: FeedView_onEntriesUpdated :: line 470
JS frame :: resource://brief/Storage.jsm :: FeedProcessor_executeAndNotify :: line 910
JS frame :: resource://gre/modules/Task.jsm :: TaskImpl_run :: line 319
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 932
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 813
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 747  brief.js:421
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Mar 31 2017 09:36:12 GMT-0700 (Pacific Standard Time)
Full Message: 
Full Stack: JS frame :: chrome://brief/content/brief.js :: getTopWindow :: line 421
JS frame :: chrome://brief/content/feedview.js :: FeedView_onEntriesUpdated :: line 470
JS frame :: resource://brief/Storage.jsm :: FeedProcessor_executeAndNotify :: line 910
JS frame :: resource://gre/modules/Task.jsm :: TaskImpl_run :: line 319
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 932
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 813
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 747  brief.js:421

**Comment by tanriol** [comment] 2017-03-31 16:51
Wow, what an interesting trace! What's your Firefox version?

**Comment by davimack** [comment] 2017-03-31 17:06
52.0.1 (32-bit) version.  Running add-ons:
<img width="342" alt="capture" src="https://cloud.githubusercontent.com/assets/12926523/24560958/c0767e8e-15f9-11e7-87a8-6949ecdd2097.PNG">

**Comment by davimack** [comment] 2017-03-31 18:21
OK, applied FF update to 52.0.2 & it seems to have resolved the issue.  Could this have been due to me accepting a FF update but not restarting the browser?  Because that's what looks to have just happened.

**Comment by tanriol** [comment] 2017-03-31 18:52
Ok, I could not reproduce this at all, but that may have been due to OS differences (I'm on Linux). Looked pretty weird... maybe some kind of a one-off addon bug that corrupted some state.

Anyway, the next version (2.3) should not be affected as it does not have the affected code at all due to e10s-related refactoring. It will be released in under two weeks.

**Closed by tanriol** 2017-03-31 18:52 UTC
