### ISSUE TITLE
Subscribed Feeds folder ID keeps changing

### ISSUE THREAD

**Issue by Bundaboy** [ancestorak/brief#244] opened 2017-05-22 02:00 UTC
This seems to be more an FF problem than a Brief problem except for the fact that it stops Brief from working as we are used to.

It seems that, for some reason, FF (53.0.3) seems to have changed the way bookmarks work and you cannot rely on the ID of a folder remaining static, and thus Brief is creating a new, empty, "Subscribed Feeds" folder on a regular basis.  It can be fixed by moving the contends of the old "Subscribed Feeds" across to the new folder each time but that is rather tiresome.

**Comment by tanriol** [comment] 2017-05-22 17:01
Have not seen such a problem on Firefox up to Nightly 55. Have you installed some new extensions, and/or doing something unusual with Sync, and/or restored bookmarks from backup multiple times?

**Comment by Bundaboy** [comment] 2017-05-23 08:57
No, nothing that hasn't been there for yonks, I don't use sync, and I only did a back up after I noticed this was happening and was worried I would lose all my feeds.

It's a strange one.

**Comment by Bundaboy** [comment] 2017-07-03 07:38
Is there no one else experiencing this problem?

**Comment by Keith94** [comment] 2017-07-04 12:07
I think I had this happen when I import an .OPML file manually in Brief.

**Comment by Bundaboy** [comment] 2017-07-05 02:48
Thanks but my problem happens all by itself, especially when starting up. Cheers.

**Comment by monkie-snake** [comment] 2017-07-11 11:37
I'm also having this problem. I tried re-installing the add-on but the problem persists.
I don't use sync, but I imported the feeds from an opml file a long time before the issue started.

**Comment by tanriol** [comment] 2017-07-11 12:00
@Bundaboy, @monkie-snake, do you have other add-ons installed? Can you list them please?

**Comment by Bundaboy** [comment] 2017-07-11 12:17
@monkie-snake, I also once imported the feeds from an opml file a long time before the issue started.

@tanriol I have previously tested by disabling ALL add-ons bar Brief and the problem persists, HOWEVER I haven't tried it without Brief enabled as I had dismissed brief as the source of the problem (otherwse every one would be experiencing it), however it IS possible that there could be some interaction between FF and Brief that isn't the normal case, it will be a pain but I should test to see if the folder ID is modified when Brief is disabled. I will report back ASAP.

**Comment by monkie-snake** [comment] 2017-07-12 20:12
@tanriol Sorry, too many to mention, but I've made a new profile and re-installed all my add-ons and settings and the problem seems to be gone (fingers crossed).

**Comment by tanriol** [comment] 2017-07-12 20:47
@monkie-snake Glad to hear your Firefox is working fine!

**Comment by Bundaboy** [comment] 2017-07-13 23:37
@monkie-snake 
How do you normally start your FF session manually, or in the Windows startup process? (assuming you are using windows).

I had the latter, but I somehow got the impression that the recreation of the subscribed feeds folder was happening if a second instance of FF was started. As I recently had a problem whereby W7 started loading OE instead of Windows Mail (as I had set it up to do) all by itself, I decided to remove FF from the startup and start it manually - since doing that I have not had the folder recreation problem.

Now this doesn't explain all of the mystery (like the fact that the recreation sometimes happened mid-session), so it may well be a red herring, but if your configuration is something similar that would lend some weight to my theory.

**Comment by monkie-snake** [comment] 2017-07-14 10:41
@Bundaboy I start it manually (windows) using a shortcut with the profile name in the command line.

I've had the problem again today, but I can't recreate it even after disabling and re-enabling extensions/themes. It seems (for me) the problem relates to the first run of the day, whether it's due to the date change or waking my computer from suspension.

I'll keep testing and let you know what I find.

**Comment by eberhardweber** [comment] 2017-09-19 15:53
I had three new "Subscribed Feeds" folders created in my bookmarks a few days ago. My Brief feeds were evenly split between two of these folders, and the two others were empty. I didn't think that much of it given that I'm using the development version. Is this the same thing that's happening to the rest of you?

**Comment by tanriol** [comment] 2017-09-19 18:15
> I had three new "Subscribed Feeds" folders created in my bookmarks a few days ago.

There is a rarely occurring problem with Brief that I haven't been able to reproduce reliably yet. Still, with 2.4.0a3 it should become even more infrequent than before.

> My Brief feeds were evenly split between two of these folders, and the two others were empty.

This one is *very* unlikely to be Brief's fault as Brief never moves your bookmarks between folders.

**Comment by Bundaboy** [comment] 2017-09-19 22:16
It is unlikely to be *exactly* the same problem unless you have added the feeds found in the last "subscribed feeds" folder since it was created - Brief does not move the feeds from one folder to another.

If you did create new feeds they would go into the newest created folder, but, also, the feeds in the previously created folder(s) would no longer appear, and be checked by, Brief.

I have found that a new "subscribed feeds" folder is created *almost* every time that FF is started up indirectly, and hardly ever when started up directly, alas that *almost* makes it hard to point a finger.

**Comment by Bundaboy** [comment] 2017-09-19 22:26
@tabriol, well... if Brief is relying on a specific FF behaviour but FF doesn't guarantee that behaviour then it is at least arguable that Brief is *part* of the problem.

On thing is certain, Brief CANNOT rely on FF maintaining the same ID for a specific folder between sessions.

One possible cause for this problem, and one that would explain the intermittency of the issue, is if Brief is checking for the existence of the "subscribed feeds" folder before FF has added it to it's internal list at session start up. This would make it a timing issue and therefore would explain the intermittency AND they fact that some people don't experience the problem (i.e. they have newer, faster, machines/drives/etc.).

**Comment by tanriol** [comment] 2017-09-19 22:33
@Bundaboy The WebExtension version will have to drop the "feeds are just live bookmarks" concept anyway, as there's no Live Bookmarks API for WebExtensions yet. That's why I currently treat this problem as temporary and rather low priority - it will be gone in two months anyway. I don't want many users to be affected during the transition, but have no time to search for the real root of this problem.

**Comment by Bundaboy** [comment] 2017-09-19 23:00
*@tabriol*, great, I can work around it until then. Cheers.

**Comment by tanriol** [comment] 2018-03-24 23:10
The folder ID related part was mostly dropped in WebExtensions migration, so I'm closing this bug.

**Closed by tanriol** 2018-03-24 23:10 UTC
