### ISSUE TITLE
Speed of Feed-Updates

### ISSUE THREAD

**Issue by Freudentaumel** [ancestorak/brief#254] opened 2017-08-18 20:20 UTC
1

It would be possible to speed up loading times for new feeds. Currently, 19 feeds need 35 seconds.

**Comment by Keith94** [comment] 2017-08-18 20:24
Maybe try adjusting `extensions.brief.update.defaultFetchDelay` in about:config.

**Comment by Freudentaumel** [comment] 2017-08-18 20:33
https://www.pic-upload.de/view-33762346/github.png.html
Which settings do you recommend, Keith?

**Comment by tanriol** [comment] 2017-08-18 20:51
You can decrease `extensions.brief.update.defaultFetchDelay` to something like 500 (half a seconf per feed). However, note that the less time it takes to update everything, the more lagging you may feel during that time. I'm planning to rework this in the WebExtension version as parsing will be moved to a separate worker thread.

**Comment by Freudentaumel** [comment] 2017-08-18 20:51
I am new here. Therefore I´d like to know what a **T-support-question** is.

**Comment by tanriol** [comment] 2017-08-18 20:54
I've marked this issue as a support question, not a bug that needs to be fixed. There are many issues and they need some classification to distinguish between those that require some work and those that do not.

**Comment by Freudentaumel** [comment] 2017-08-18 20:59
Hello tanriol,

I have adjusted the value to 500 and the update for the 19 feeds now takes only 13 seconds.

And thanks for the correct classification of my thread.

Friendly greeting
Gerhard

**Comment by tanriol** [comment] 2017-08-18 21:39
Ok, closing the thread as the question is answered.

**Closed by tanriol** 2017-08-18 21:39 UTC
Labels: T-support-question
