### ISSUE TITLE
Performance issues while Brief is updating feeds

### ISSUE THREAD

**Issue by VillageCatDad** [ancestorak/brief#308] opened 2017-11-24 00:43 UTC
I've noticed that when Brief is updating feeds per my setting (15 min), Brief's responsiveness is poor and spotty.  Difficult to mark articles as read, for example.  Not frozen, just no response.  Have to wait for update to finish before I can keep reading.  I've not seen this with any other extension or app on my iMac.

**Comment by tanriol** [comment] 2017-11-24 10:48
Debugging the issues now. The problem seems to be the update process locking the IndexedDB for a long time (even seconds!), but I haven't found the root cause yet.

**Comment by tanriol** [comment] 2017-11-24 23:20
Please test 2.5.3 which should have (mostly) fixed this problem.

**Comment by VillageCatDad** [comment] 2017-11-24 23:28
Will do and will let you know.  Slow news cycle (not many updates) on my feeds at this time, so will wait for a bigger set of updates before I provide feedback.  Appreciate the quick response, and hope the changes work!

**Comment by VillageCatDad** [comment] 2017-11-25 17:08
Ok, it's better but not fixed.  Appreciate the effort!  What I'm noticing now is that the non-responsiveness occurs most frequently when I'm reading a folder, and a new article appears which is 'above' or newer then the one that is currently first (at top of list).  When that happens, I can't do anything with the current article.  If I pick another folder and go right back to the original one, the new article appears first, and I can proceed normally.  Hope that helps!

**Comment by tanriol** [comment] 2017-11-25 23:02
@VillageCatDad This one actually sounds not like performance issue, but like feedview state corruption. There will be a small refactoring in the next version, so it may be better.

**Comment by VillageCatDad** [comment] 2017-11-26 00:40
Ok, thanks for the update!  BTW, I have 30+ yrs as a software developer, so I understand testing and non-deterministic results.  Will continue to feed you what I notice.  Good app, thanks again for bringing this forward for FF57+.

**Comment by tanriol** [comment] 2017-11-27 15:08
Should be fixed in 2.5.5 (0fd57dac1e9de02919961027aed0c2f3fad7628f and 8c2c86383d15904c77f927f2fa8dfccce48f57fd).

**Closed by tanriol** 2017-11-27 15:08 UTC
