### ISSUE TITLE
suddenly many entries of the Youtube-Abos are marked as "updated"

### ISSUE THREAD

**Issue by Biggizen** [ancestorak/brief#176] opened 2016-01-24 23:14 UTC
Hello,

yesterday Brief marked many old entries of many of my Youtube-Abos as "updated" (orange in brackets). What does "updated" mean? My Brief never set an "updated" tag before and now suddenly it does that for so many entries from one moment to another. I checked at some entries, if there was something changed (updated) on the Youtube-page, but have not seen anything. What happened?

I hope my English was not too bad, so you understand what I tried to say. Thank you for answering!

**Comment by tanriol** [comment] 2016-01-25 05:08
The RSS/Atom protocols have a way to mark entries updated, and Brief is configured to detect these, mark them as "(updated)" and mark them back unread. This function of Brief was broken around version 2.0 and fixed in 2.2 released just recently.

As for Youtube, I may guess that it updates the entries when comments, likes or maybe even views changes. You may set "Don't mark changed items back as unread" in the feed properties to avoid the updates littering the unread views.

**Comment by Biggizen** [comment] 2016-01-25 10:51
O. k. thank you for the quick reply.

**Comment by kotarou3** [comment] 2016-01-30 11:49
Only problem with marking them one-by-one is when you're subscribed to a huge number of channels. Something like #175 would work, or alternatively maybe some hardcoding for youtube feeds to ignore view/like/comment updates specifically

**Comment by davimack** [comment] 2017-04-10 20:33
Agree: the plugin needs some means of setting this property across an entire folder (or all feeds), rather than on an individual basis.  I have several hundred feeds & have been playing whack-a-mole with them showing up as updated (where something about the feed itself has changed, so Brief pulls down 50 or 100 posts) on a case-by-case basis.  I would far rather say "apply to all" and be able to go back and set it the other way on individual feeds.

**Comment by tanriol** [comment] 2017-04-10 21:45
I have some ideas on this topic, but WebExtension transition will be a higher priority in the following days.

**Comment by tanriol** [comment] 2017-11-22 21:35
Closing in favour of #302.

**Closed by tanriol** 2017-11-22 21:35 UTC
Labels: T-support-question

**Comment by tanriol** [comment] 2017-11-27 17:31
Deduplication.

Duplicate of #178.
