### ISSUE TITLE
[XUL->HTML] Firefox will stop XUL in Firefox 57 (november 2017)

### ISSUE THREAD

**Issue by jibe-b** [ancestorak/brief#252] opened 2017-08-04 16:46 UTC
Hence, Brief will need to switch to WebExtension.

This will benefit to #75

Depending on how easily I catch up with XUL and WebExtensions, I may do my part in this.

**Comment by tanriol** [comment] 2017-08-04 17:26
Duplicate of #248, let's discuss there.

**Closed by tanriol** 2017-08-04 17:26 UTC
Labels: S-duplicate
