### ISSUE TITLE
Organise does nothing

### ISSUE THREAD

**Issue by sabret00the** [ancestorak/brief#155] opened 2015-08-30 17:54 UTC
Selecting organise, previously I could assign brief to look at the folder where all of my RSS feeds are, in 2.0.1 I'm unable to do that. It opens the windows but doesn't seem to take.

**Comment by tanriol** [comment] 2015-08-31 06:41
The Organize function is there to let you rearrange the feeds you have. Brief 2.0 does not allow to change the root folder (not my decision, and I don't like it). However, you can just put your feeds into the folder Brief considers its root and rename it as you wish.

**Comment by tanriol** [comment] 2016-01-11 21:57
Closing as a duplicate of #156.

**Closed by tanriol** 2016-01-11 21:57 UTC
Labels: regression, support question
