### ISSUE TITLE
Certain feeds remark themselves as unread.

### ISSUE THREAD

**Issue by QuDu43bChhiONNVlgkoy** [ancestorak/brief#240] opened 2017-05-13 03:34 UTC
One of the feeds that does it: http://awkwardzombie.com/awkward.php

Every time I update my feeds it keeps on marking the 2 most recent posts as unread, despite making sure I marked them as read.

Firefox 53.0.2, Brief version 2.3.0.

**Comment by tanriol** [comment] 2017-05-13 17:20
Closing as a duplicate of #238

**Closed by tanriol** 2017-05-13 17:20 UTC
Labels: S-duplicate
