### ISSUE TITLE
Items in MediaWiki feeds duplicated upon each refresh

### ISSUE THREAD

**Issue by dieudo4** [ancestorak/brief#141] opened 2015-03-10 10:16 UTC
Consequences of that : at each refresh it doubles the number of detected articles in feed. If the time between two update is ten minutes, it gives ten minutes difference between the articles dates.

I Use FF 36.0.1 on OSX 10.10.2 and on Ubuntu 12.04LTS : same problem on both systems for example on the feed available on this page : 
https://www.mediawiki.org/wiki/Special:RecentChanges

It's a painful situation, since I can't see any equivalent of Brief to follow changes on websites based on MediaWiki : (

Thank you for any clue on that issue !

**Comment by dieudo4** [comment] 2015-03-10 11:49
For the moment the best alternative I find is this one : 
https://addons.mozilla.org/fr/firefox/addon/bamboo-feed-reader
although it's not as good for presenting the MediaWiki based websites RecentChanges : colors are missing in Bamboo and are present in Brief.
I hope this bug can be fixed !

**Comment by AussieD** [comment] 2015-03-10 13:15
I just added the feed you cited (https://www.mediawiki.org/wiki/Special:RecentChanges) and I have reproduced what you are talking about.

I'm not a dev, so I cannot give any technical insight as to what is happening. I put that feed on a two-minute refresh cycle and it has now managed to rack up an item count of 799 (47 news items x 17 refreshes).

tanriol seems to have taken over the ongoing development of Brief. He's usually very proactive and he'll chime in when he reads this.

Not sure how many feeds you subscribe to, but this feed is the ONLY one I have which is misbehaving (I subscribe to 150+ feeds). Makes me wonder whether the problem is at the source of the feed. tanriol will know...

Time for me to delete this feed...

**Comment by tanriol** [comment] 2015-03-10 13:32
Reproduced, looks like the ad-hoc fix for MediaWiki is one of the causes. Searching for the other one...

**Comment by dieudo4** [comment] 2015-03-10 15:20
Thank you tanriol for your proactivity : )

Same problem is observed on other websites based on MediaWiki : Wikipedia, etc…

**Comment by ancestorak** [comment] 2015-03-22 00:09
We actually have some rules in the feed processor specifically to avoid this problem with MediaWiki feeds. Perhaps they have changed something, I'm gonna investigate.

**Comment by dieudo4** [comment] 2015-03-22 07:20
Thank you : )

**Comment by Keith94** [comment] 2015-12-27 09:13
Any progress on this? It's a really annoying bug...

**Comment by tanriol** [comment] 2015-12-27 13:37
Thank you for the reminder. So, this is caused by a special MediaWiki handling introduced way back in 2007. Wondering whether it's still required...

**Comment by dieudo4** [comment] 2015-12-28 17:23
It would still be indeed appreciated : )

**Comment by tanriol** [comment] 2016-01-12 22:51
Should be fixed (or at least mostly fixed) in the beta version (Brief 2.2b1).

**Comment by tanriol** [comment] 2016-01-13 16:57
Closing this bug for now as I can't reproduce it with 2.2b1.

**Closed by tanriol** 2016-01-13 16:57 UTC
Labels: bug, regression
