### ISSUE TITLE
Feeds list stopped working on FF36.0

### ISSUE THREAD

**Issue by nicorac** [ancestorak/brief#139] opened 2015-02-26 16:01 UTC
Just updated to FF36.0.
The list of feeds on the left can't be clicked anymore so the content always show the "all elements" view.

Right click on feeds works ok (mark feed as read, update feed, ...).

**Comment by Dubs1** [comment] 2015-02-26 19:18
Same here as nicorac

**Comment by tanriol** [comment] 2015-02-26 20:06
Are you using the development version 2.0b3? If not, this is expected. We're going to releease it as 2.0 final as soon as all the translations are finished. For now, please use [Brief 2.0b3](https://addons.mozilla.org/firefox/downloads/file/294808/brief-2.0b3-fx.xpi).

**Comment by nicorac** [comment] 2015-02-27 09:11
Didn't know about Beta existence.
Brief 2.0b3 works (even if I don't like the new interface...).
Thanks for pointing it out.

**Comment by Just4code** [comment] 2015-02-27 16:20
I'd also like to thank you for your efforts of keeping good old brief alive.
A few remarks that might help debugging.

Using FF36.0 on three different XP & win7.
Removed old Brief, installed 2.0b3, deleted brief.* and started with a clean DB.
My old feeds were kept without problem and reappeared on the left panel.
Updating feeds, adding, removing presents no problems.
There is a problem with bookmarking (staring) items.
The same behavior was confirmed and replicated on all three systems as follows.
While reviewing the feeds, an item -or more than one - is marked 'stared' (bookmarked).
Then select bookmarks on the panel on the left. Select expanded view (from the buttons on the top of page).
Try to remove the star (unbookmark) from the items controls.
You will notice that it takes two clicks.
The first click removes the bookmark from places.sqlite - but the star remains and also the item remains in the bookmarked list.
The second time the star is finally removed.
Also, after clicking to remove the star, the view is refreshed and most of the times items are lost from the display. Sometimes, not all of the items are lost but you have to select 'all items' on the left and then 'bookmarks' again to view remaining items.
I just hope that does not corrupt the database.
It would also be nice if stars were also visible while in compressed list (just the tiles view) otherwise you have no way to remove the stars while in this compressed view.

I must also admit that the positioning of icons was more practical with old brief, but there is always a field for improvement with every application.
Thank you, keep up the good work.

**Comment by bobular** [comment] 2015-03-02 09:32
Great stuff - came to report same problem - beta working fine for me...

**Comment by r03ert0** [comment] 2015-03-07 22:58
Same issue. Will try the beta

**Comment by jnachtigall** [comment] 2015-03-09 08:48
Could the beta be released asap. Brief ist not working and most people are non-devs and will not know what github etc. is...

Also I do not want to fiddle around with installing betas but just use the FF autoupdater.

Currently, brief is not working at all in FF 36 due to this bug :-(

**Comment by sleek22** [comment] 2015-03-10 00:44
To install the latest beta, go to the Brief add-on site I link to below and click on "Development Channel".
The link is there.

https://addons.mozilla.org/en-US/firefox/addon/brief/

**Comment by babylon4** [comment] 2015-03-12 02:12
I have been using Brief for a long time, and it knows which posts I have read and which I have not.  When FF updated to 36.0, Brief 1.7.3 (my current version) stopped working.  The link that sleek22 pointed to in the development channel asks if I want to "add to Firefox" Brief 2.0b3.  If I click yes, will I end up with two different Brief installations?  Will 2.0b3 be a brand new installation that doesn't know which posts in my RSS feeds I have marked read and which are unread?

**Comment by AussieD** [comment] 2015-03-12 03:49
It should simply update your Brief Add-on to v2.0b3 (ie. replace 1.7.3 with 2.0b3). Being an update, rather than creating a new 'installation', it should retain your existing feeds/history.

**Comment by babylon4** [comment] 2015-03-13 03:47
That works!  Thanks!  By the way, it looks like 2.0b3 took away the "Unread" view (which I love), and yet in the Options you can configure the Unread view even though it doesn't exist.

**Comment by AussieD** [comment] 2015-03-13 04:00
The ability to filter for only unread items still exists. You can use the "D" keyboard shortcut or use the icon button highlighted in the following screenshot:

![01](https://cloud.githubusercontent.com/assets/10163362/6632837/02cd40e0-c978-11e4-8646-6cf8bd5a0d05.png)

If you ever forget what an icon does, simply hover over it for a moment and a short tool tip will pop-up.

**Closed** 2015-03-22 00:30 UTC
