### ISSUE TITLE
Unable to subscribe

### ISSUE THREAD

**Issue by ParadoxSystem** [ancestorak/brief#357] opened 2018-05-12 01:28 UTC
After updating to Firefox 60.0, I am unable to subcribe to new feeds and get this error message instead. Brief version is 2.5.5. Windows 10. 
![image](https://user-images.githubusercontent.com/9489560/39952313-e75bfdc8-5548-11e8-9658-705d7e23f930.png)

**Comment by JesperSjoquist** [comment] 2018-05-12 09:32
Also having problems since upgrading to Firefox 60 but for me the Brief option is not even there anymore:

![image](https://user-images.githubusercontent.com/30660/39955979-249b13f6-55d8-11e8-8cea-9e3b9be35be0.png)

**Comment by n8v8R** [comment] 2018-05-13 19:04
this a know bug https://github.com/ancestorak/brief/issues/343

**Comment by tanriol** [comment] 2018-05-13 19:11
Duplicate of #343, closing.

**Closed by tanriol** 2018-05-13 19:11 UTC
