### ISSUE TITLE
new tag in background

### ISSUE THREAD

**Issue by bb84000** [ancestorak/brief#315] opened 2017-11-27 07:01 UTC
Hello, 
it is not an important issue, but with the new firefox (with switch to new tab activated in FF settings) when i click on the title of a new, the new tab remain in background instead to go foreground as it did with pre FF57 version. Il is perhaps a FF issue, bur is there a workaround possible in Brief ?
Thanks,

bb84000 from France

**Comment by tanriol** [comment] 2017-11-27 13:04
Duplicate of #296

**Closed by tanriol** 2017-11-27 13:04 UTC
