### ISSUE TITLE
Empty feed list after 2.4.0a2

### ISSUE THREAD

**Issue by JesperSjoquist** [ancestorak/brief#262] opened 2017-09-16 21:42 UTC
After restarting Firefox, the list of subscribed feeds is empty. I noticed I had been upgraded to Brief 2.4.0a2. 

The actual content from the subscribed feeds is still show but the sources are no longer visible. See attached screenshot.

I can't say for sure that it's connected to 2.4.0a2 but I don't think I have restarted Firefox since before that version was published.

![brief-empty-feed-list](https://user-images.githubusercontent.com/30660/30516221-97649214-9b38-11e7-879c-c3a4d151fc1c.jpg)

**Comment by tanriol** [comment] 2017-09-16 21:45
Please check using "Organize" that Brief did not create a new home folder for feeds. If it did, this is a known bug that I haven't yet found a way to fix in the legacy extension.

**Comment by JesperSjoquist** [comment] 2017-09-16 22:03
That is indeed what had happened! Copying everything from the old folder to the new one solved the problem. Thank you!

**Comment by JesperSjoquist** [comment] 2017-09-18 07:29
This has now become a reproducible issue after every restart of Firefox, even after the attempted fix in 2.4.0a3.

One thing that may be a factor in this is that I have a large number of tabs open, at least 50+, which are restored with Session Manager on each restart. If this is a timing issue as you suspected with the 2.4.0a3 fix, that might cause problems. I haven't had this problem before 2.4.0a2 though so I'm not sure what changed. (it might have started in 2.4.0a1, not sure about when I restarted the browser during that period)

You mention the "legacy extension", is there a newer version available?

**Comment by tanriol** [comment] 2017-09-18 08:00
> You mention the "legacy extension", is there a newer version available?

Unfortunately, the WebExtension version is not here yet :-(

Could you please check two things?

First, please open `about:config` before restarting and note the value of `extensions.brief.homeFolder`. After restarting, without moving feeds, try setting `extensions.brief.homeFolder` to the value you noted. This should get the feeds back, unless something really changes its ID every restart. Does it?

Second, Brief should now be logging failed attempts to get the home folder, so after a restart when it reproduces please open the Firefox console (Ctrl+Shift+J) and check there for errors.

**Comment by JesperSjoquist** [comment] 2017-09-18 08:25
The homeFolder value does indeed increase by 1 every restart. Resetting it to the previous one brings the feeds back, but the ID is up by 1 by the next restart anyway.

The only log from Brief that shows up is "Brief: extension startup", no sighting of the exemption you try to log. Seems like it thinks the try works the first time, albeit with the wrong ID.

**Comment by JesperSjoquist** [comment] 2017-09-18 08:50
So, amateur theory hour:
Since I have a massive amount of tabs to restore, startup is slow. So I'm thinking maybe this block is the culprit:
```javascript
this.homeFolderID = Prefs.getIntPref('homeFolder');
this.ensureHomeFolder();
```
My thinking is that Prefs.getIntPref('homeFolder'); is run too early and returns -1 because there's too much else going on at the moment. 
(I have really no knowledge of how the Firefox startup process works or how other extensions like Session Manager might mess with it, hence amateur hour)

If I understand it correctly, if Prefs.getIntPref('homeFolder'); returns -1, then ensureHomeFolder() creates a new ID. Or at least it could be one possible culprit.

**Comment by tanriol** [comment] 2017-09-18 09:17
> Resetting it to the previous one brings the feeds back

The folder IDs are stable across restarts, good...

> The only log from Brief that shows up is "Brief: extension startup", no sighting of the exemption you try to log.

Ok, now this seriously puzzles me. Could you please try one more check?

Make Brief see the feeds. Note the `homeFolder` value.

Disable Brief, *refresh* `about:config` (F5) and check that the value is still there.

Restart Firefox, still with Brief disabled. Is `homeFolder` visible in `about:config` now? Which value?

Now enable Brief. Does it show the feeds correctly? What's the `homeFolder` value?

If this does not shed light on the problem, I'll make a special Brief build with extra debug logging.

**Comment by JesperSjoquist** [comment] 2017-09-18 09:45
Ok, leaving Brief disabled, I.e. not loaded in any tab, the homeFolder value still increases by 1 every restart (tried it a couple of times to make sure).

Now opening brief, it still has the same problem. And the log still doesn't show the exemption :(

**Comment by tanriol** [comment] 2017-09-18 09:47
Sorry, by "disabled" I meant not "not loaded in any tab", but "open addon manager and press the Disable button for Brief"

**Comment by tanriol** [comment] 2017-09-18 10:42
> Now, copying the feeds from the old folder to the new and restarting Firefox, the homeFolder value still stays the same and all my feeds are visible!

I still don't understand how this could help, but you're welcome to close this bug if the issue is solved for you. Glad to see it gone!

**Closed** 2017-09-18 11:00 UTC
