### ISSUE TITLE
Brief in Firefox 57+

### ISSUE THREAD

**Issue by Freudentaumel** [ancestorak/brief#276] opened 2017-11-14 12:40 UTC
I have two questions:
1) From when will Brief be compatible with Firefox57+?
2) Can I still use Brief even if I have "cleaned up" Firefox 57+? Because in this case, all add-ons have to be reinstalled.

**Comment by tanriol** [comment] 2017-11-14 12:43
1. I'm working on it right now and hope to get an alpha version tomorrow. With some regressions, but at least working.

2. I don't know the scale of that cleanup. You can lose your feed list (unlikely, but possible) and stored entries.

**Comment by Freudentaumel** [comment] 2017-11-14 12:47
1) Thank you for your quick answer and I wish you every success in the implementation.

2) I would export the feed list before from my current reader to the desktop and then import it into Brief.

**Comment by Freudentaumel** [comment] 2017-11-14 12:50
> I don't know the scale of that cleanup.

The "new" Firefox is like before, but only without the "actual" add-ons.

**Comment by primaeval** [comment] 2017-11-15 10:43
Thanks. I downgraded Firefox to 56 just for brief. Keep up the good work. We need you. :)

**Comment by Freudentaumel** [comment] 2017-11-15 15:52
I prefer to keep Firefox 57 and wait for the compatible (alpha) version.

tanriol is working on it and I want to give him the time he needs for a working version.

**Comment by primaeval** [comment] 2017-11-15 17:26
It's the Firefoxalypse according to Slashdot. There are a unhappy puppies with all their broken addons.
https://news.slashdot.org/story/17/11/13/204232/firefox-57-brings-better-sandboxing-on-linux 
I think someone said the nightlies and dev version still works but I haven't tried it.

**Comment by tanriol** [comment] 2017-11-15 22:24
The pre-alpha is in `master` now. Just a few more required but missing features...

**Comment by claytonrcarter** [comment] 2017-11-16 17:54
@tanriol do you have any tips for how to test out the alpha? I've tried running it via the `web-ext` command, as well as loading it temporarily via `Add-ons Manager > Debug Add-ons > Load Temporary Add-on` and both ways seem to go nowhere. I get access to the Brief UI, but there are no feeds and seemingly no options for adding feeds. I'm running FF 57.0 and would love to help out with testing.

**Comment by tanriol** [comment] 2017-11-16 21:08
@claytonrcarter,
First, if you've upgraded to Brief 2.4 previously, it should have saved a copy of your feed list. Haven't it?
Subscribing is done by visiting a feed (or page that links to feeds) and clicking on the Brief button inside the address bar.

**Comment by Freudentaumel** [comment] 2017-11-16 21:17
How can I install version 2.4 or a corresponding version in Firefox 57?

**Comment by Freudentaumel** [comment] 2017-11-16 21:33
Meanwhile I´ve found the answer: version 2.5.0a1.

**Comment by claytonrcarter** [comment] 2017-11-16 21:47
OK, I was missing the icon in the address bar. Normally, when I visit a feed, I was using the FF feed UI where it says "Subscribe to this feed using ..." then offers a drop down to pick how to subscribe. That doesn't appear to be working for me; it takes me to a file not found page with message "Firefox can’t find the file at chrome://brief/content/brief.xhtml?subscribe=http://blog.atom.io/feed.xml."

When I click the brief icon in the address bar, it looks like it's supposed to be showing some sort of modal confirmation, but all I get is a little triangular "tab" and the rest of the modal is collapsed, so I can't see it. It does appear to work to subscribe, though, and switching back to the Brief tab and reloading shows the new feed.

v2.5 has lost my feed list, though. I had been running an up-to-date Brief until the FF 57 update. I was able to find my old `brief.sqlite` file, so I can recreate my old list if needed. Could it not be finding my old feeds b/c it's only installed via debug/temporary install?

**Comment by tanriol** [comment] 2017-11-16 22:04
> When I click the brief icon in the address bar, it looks like it's supposed to be showing some sort of modal confirmation, but all I get is a little triangular "tab" and the rest of the modal is collapsed, so I can't see it. It does appear to work to subscribe, though, and switching back to the Brief tab and reloading shows the new feed.

It should not be showing any confirmation if there's only one possible feed here, but subscribe right away, so the tab should not appear.

> Could it not be finding my old feeds b/c it's only installed via debug/temporary install?

Hmm... not sure. Probably if the debug/temporary install uses a different addon ID. Does it keep the feeds you add across a Firefox restart?

> ...the FF feed UI where it says "Subscribe to this feed using ..." then offers a drop down to pick how to subscribe.

I haven't yet hooked into that part of the subscribe page, although I do want to.

**Comment by claytonrcarter** [comment] 2017-11-16 22:54
> It should not show any confirmation if there's only one possible feed here, but subscribe right away, so the tab should not appear.

OK, here's what I'm seeing when I click the Brief icon in the address bar:
![kapture 2017-11-16 at 17 41 35](https://user-images.githubusercontent.com/1420419/32920036-d2ca62f6-caf5-11e7-813d-acf5e2d2dc3c.gif)

> Probably if the debug/temporary install uses a different addon ID. Does it keep the feeds you add across a Firefox restart?

It does keep the feeds if I restart, but I have to reinstall the addon each time. I think you're right that it's not using the normal addon ID.

**Comment by Freudentaumel** [comment] 2017-11-16 22:57
> Meanwhile I´ve found the answer: version 2.5.0a1.

I am sorry, this version does not work at all in Firefox 57.

**Comment by tanriol** [comment] 2017-11-16 23:03
@claytonrcarter Oh, thank you, a bug indeed. Will be fixed in 2.5.0a2.

@Freudentaumel Works for me in my tests. Would be very nice if you could specify what *exactly* does not work for you.

**Comment by tanriol** [comment] 2017-11-16 23:04
Well, to be more exact, I'm testing it in 56 and using in Nightly 58.

**Comment by Freudentaumel** [comment] 2017-11-16 23:16
I can't import feeds or add a single feed.

Clicking on "Organize" does not open a window. And a click on "That's the way to do it" will also not open a window.

**Comment by tanriol** [comment] 2017-11-16 23:18
> Clicking on "Organize" does not open a window. And a click on "That's the way to do it" will also not open a window.

Yeah, I know about Organize, it's not yet there. Have you seen the Brief icon in the title bar as in [the comment above](https://github.com/ancestorak/brief/issues/276#issuecomment-345089394)?

**Comment by Freudentaumel** [comment] 2017-11-16 23:24
> Have you seen the Brief icon in the title bar as in the comment above?

No. It also no longer appears in the Firefox 57 settings.

**Comment by tanriol** [comment] 2017-11-16 23:26
Well, if Brief is not installed in the Firefox addons list, then it's not installed for some reason and sure it can't work in that case.

**Comment by Freudentaumel** [comment] 2017-11-16 23:29
But Brief **_is_** installed in the Firefox addons list.

**Comment by tanriol** [comment] 2017-11-16 23:34
Ok, if Brief shows nothing for you, could you please do the following:

- open the browser console with Ctrl+Shift+J and clear it with the "trash" icon button,
- go to the addon list, disable Brief and enable it again,
- copy any errors or warnings from that operation to a place like pastebin and post a link here (or maybe just paste them here if only a few lines)

**Comment by h4p4t3** [comment] 2017-11-17 07:28
WFM except for the kown restrictions - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

Thank you!

**Comment by Guite** [comment] 2017-11-17 08:04
From where can I install the 2.5.0a1 version?

**Comment by h4p4t3** [comment] 2017-11-17 08:08
https://addons.mozilla.org/de/firefox/addon/brief/versions/beta

**Comment by Guite** [comment] 2017-11-17 08:11
Thanks!

Seems to work fine for me, thank you!

**Comment by DuncanL** [comment] 2017-11-17 09:35
Working fine for me - feed list all present and correct having installed the 2.4 beta a while back.

Thank you @tanriol!

**Comment by SzegaX** [comment] 2017-11-17 10:38
I installed 2.5.0a1 and observed the following:
Refresh did not stop properly: the completion bar is still there, the button above is "stop" and unresponsive.
"Organize" is also unresponsive.
"Refresh now" from the dropdown menu is also unresponsive.

**Comment by tanriol** [comment] 2017-11-17 12:07
@SzegaX Was it a one-time problem or does it occur regularly? Can you reproduce it reliably?

> "Organize" is also unresponsive.

Not reimplemented yet.

**Comment by tanriol** [comment] 2017-11-17 12:34
Published 2.5.0a2 with feed properties dialog and notifications.

**Comment by SzegaX** [comment] 2017-11-17 13:06
@tanriol I cannot start the refresh manually, but the issue did not resolve with the auto-refresh either. The bar is stuck at ~90%, "stop" showing. I also cannot see the "loading" animation over feed icons in the list. Thus it might be that "refresh now" works, but I have no way of telling besides chancing upon a feed that updated in the last hour.
I will install the newest version.

**Comment by SzegaX** [comment] 2017-11-17 13:12
@tanriol Ran a manual refresh after the install of a2, no change. I should note that I have a feed that had a tendency to load ad infinitum sometimes, but the "stop" button took care of it until now.

**Comment by tanriol** [comment] 2017-11-17 13:18
> I also cannot see the "loading" animation over feed icons in the list.

Not implemented yet, sorry.

> I should note that I have a feed that had a tendency to load ad infinitum sometimes, but the "stop" button took care of it until now.

There should be a time limit of 25 seconds on the load, so it should terminate rather quickly. Can you share the link for easier testing?

**Comment by SzegaX** [comment] 2017-11-17 13:23
@tanriol Sure, it is http://www.giantitp.com/comics/oots.rss
I may have run out of patience in the past (so the 25s might have been not over yet), but now it has been sitting like that for minutes. I cannot confirm this is the feed causing the issue due to the lack of loading animations.

**Comment by claytonrcarter** [comment] 2017-11-17 13:30
@tanriol Thank you, thank you! I have installed 2.5a2 (via the link https://addons.mozilla.org/en-US/firefox/addon/brief/versions/beta) and it seems to be working now.

It did not import my old feeds from 2.4, but I was able to find them in the old sqlite db on disk and resubscribe to each. 

The only feed that didn't work was https://adamwathan.me/rss/ with the following output in console. (That feed has acted weird in previous versions, with dates of entries being off by significant margins.)
```
Need a new feed 77ae803682a843fa8fcb14e993186b50a5b833b2 from Object { title: "Adam Wathan's Blog", url: "https://adamwathan.me/rss/" }  database.js:230:13
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  (unknown)
ReferenceError: text is not defined
Stack trace:
url@moz-extension://1a9d09fc-7ab3-b544-a255-5b43bd91196b/scripts/updater.js:497:17
_parseNode@moz-extension://1a9d09fc-7ab3-b544-a255-5b43bd91196b/scripts/updater.js:352:33
entry@moz-extension://1a9d09fc-7ab3-b544-a255-5b43bd91196b/scripts/updater.js:446:25
_parseNode@moz-extension://1a9d09fc-7ab3-b544-a255-5b43bd91196b/scripts/updater.js:352:33
fetchFeed@moz-extension://1a9d09fc-7ab3-b544-a255-5b43bd91196b/scripts/updater.js:308:22
  (unknown)
```

**Comment by Keith94** [comment] 2017-11-17 13:31
@tanriol Will importing feeds be implemented soon?

**Comment by tanriol** [comment] 2017-11-17 14:59
@Keith94 Working on it right now!
@claytonrcarter Thanks for the link, bug found and fixed!
@SzegaX Works for me, but I'll try to restore the loading indicators soon.

**Comment by fichtennadel** [comment] 2017-11-17 15:09
First: thumbs up for the beta, works fine for >90%

Two things I've realized:

- some feeds do not load and refresh stops on them 
- "Stop" button is defunct

How to find out which feed causes the problem?

**Comment by claytonrcarter** [comment] 2017-11-17 15:32
@fichtennadel There may be a better way, but I was able to do quite a bit of debugging and tinkering this way:
1. Open Add-ons (`shift-command-a` on Mac)
2. Next to "Search all add-ons" box there is a ⚙️ icon. Click the gear and select "Debug add-ons"
3. Up top, click "Enable add-on debugging"
4. Find "Brief" and click the "Debug" link underneath it.
5. You'll get a popup from the debugger asking if you will allow the incoming debugging connection. Select "OK".
6. A new dev tools window will appear and Brief will print output and debugging statements to the "Console" panel. (If you're unfamiliar, "Console" is listed up top, inbetween "Inspector" and "Debugger".)

Brief doesn't seem to be logging which feeds it's updating, but exceptions it encounters will be printed and those might be helpful.

**Comment by neltnerb** [comment] 2017-11-17 16:02
Thanks so much for the great add-on! In addition to the import feed button not working (reported already), unsubscribing from a feed does not remove it and the "See how to do it!" link when you first open it is dead. Other than that, 2.5.0a2 seems to do what is expected.

**Comment by tanriol** [comment] 2017-11-17 21:01
New alpha - 2.5.0a3. Features feed import, reliability fixes and working subscribe button in the feed preview UI.

**Comment by Keith94** [comment] 2017-11-17 21:08
I tested importing from Feedly but more than half of my feeds seem to be missing in Brief.

**Comment by tanriol** [comment] 2017-11-17 21:18
The import may take some time, unfortunately... that bothers me too, but no good idea on what to do instead.

**Comment by fichtennadel** [comment] 2017-11-17 21:39
Subscribe button does not show anymore in 2.5.0a3, for example on http://derstandard.at/

Switched back to 2.5.0a2, ok there.

**Comment by tanriol** [comment] 2017-11-17 22:07
@fichtennadel Thank you for reporting, fixed in alpha 4.

**Comment by fichtennadel** [comment] 2017-11-17 22:38
Subscribe button is back in a4, but list is empty:

![image](https://user-images.githubusercontent.com/2324670/32972023-5af656da-cbf0-11e7-8116-3c95daa6f908.png)

**Comment by tanriol** [comment] 2017-11-17 22:47
Reproduced and fixed, thank you.

**Comment by tanriol** [comment] 2017-11-18 01:16
Version 2.5.0a5: drag'n'drop for Organize and the fix mentioned above.

**Comment by eberhardweber** [comment] 2017-11-18 01:23
I too tried importing my feed backup now that it is possible on a5, but not all of them ultimately got imported. I waited until no more feeds were added, and the importing process stopped at 999 unread feeds. Perhaps that's where it also stopped adding more subscriptions?

**Comment by miforefox** [comment] 2017-11-18 06:39
First of all thank you for your efforts to make this great add-on again.
Unfortunately, even with 2.0.5a5, i have some problems. It refreshes fine all my previous feeds but it just shows them altogether in "all items" or "today" categories but it does not show each feed individually so that I can view only one feed.

![default](https://user-images.githubusercontent.com/33774971/32977717-9957e560-cc3b-11e7-902d-8e14eba8ea6d.png)

I can add a new feed and the new feed is shown individually as normal.
Is there at least any way to delete all my feeds and start again by manually adding my previous feeds in order to see each feed individually?

**Comment by creeker** [comment] 2017-11-18 07:11
2.5a5 worked fine for me.  Longtime Firefox user, with a bunch of existing feeds that I was prepared to reload manually, but no need.  I am on Win7Pro 64 bit.

Brief located and updated feeds for all my subscribed sources, displayed them as I expected to see them, and generally behaved well.  Videos in preview in the right hand pane didn't work, but that's not the end of the world.

A simple and great product; thanks from a long-time happy user.

**Comment by tanriol** [comment] 2017-11-18 09:05
@miforefox Could you please open the developer console with F12, reload the page and tell me the errors? This sounds like a nasty bug that has to be fixed...

**Comment by miforefox** [comment] 2017-11-18 09:25
Brief: update pref pagePersist to {"startView":"all-items-folder","closedFolders":"_","tagList":{"width":""},"sidebar":{"width":"351px","hidden":false},"view":{"mode":"headlines","filter":"unread"}}
prefs.js:30:9
Brief: opening database in persistent storage
database.js:45:9
Brief: 26 feeds in database
database.js:176:9
Brief: opened database with 476 entries
database.js:55:9

**Comment by miforefox** [comment] 2017-11-18 09:30
Brief: update pref pagePersist to {"startView":"all-items-folder","closedFolders":"_","tagList":{"width":""},"sidebar":{"width":"351px","hidden":false},"view":{"mode":"headlines","filter":"unread"}}
prefs.js:30:9
Brief: opening database in persistent storage
database.js:45:9
Brief: 26 feeds in database
database.js:176:9
Brief: opened database with 476 entries
database.js:55:9

**Comment by tanriol** [comment] 2017-11-18 09:34
Nothing suspicious... weird. If you're ok with sharing your feed list, could you please enter the following in the console's bottom line and paste the output [as a gist](https://gist.github.com/)?
```
for(let f of Database.feeds) console.log(JSON.stringify(f))
```

**Comment by miforefox** [comment] 2017-11-18 09:39
Anyway to just delete everything related to brief and start over fresh (i don't mind re-entering the feeds).

**Comment by lmaonator** [comment] 2017-11-18 10:55
Reddit RSS feeds don't seem to work for me anymore with the latest alpha. I can add them but it's not showing any posts for them.
For example https://www.reddit.com/r/aww/.rss
![grafik](https://user-images.githubusercontent.com/33778605/32979509-af989cf0-cc56-11e7-8dad-84eac4eaf83b.png)

They worked fine in earlier versions before FF 57

**Comment by tanriol** [comment] 2017-11-18 12:22
Beta 1, hopefully, the final before release.

Quick and more reliable OPML import, entry expiration is working now, minor organize fixes, parent chain corruption fixup ( @miforefox, this is likepy to help your invisible feeds).

What's missing of 2.5 features: folder creation and renaming, drag'n'drop into an empty folder, possibly full-text search. Entry tags are not in 2.5, they will return in a later version.

**Comment by tanriol** [comment] 2017-11-18 12:26
@lmaonator The feed you linked to works for me.

**Comment by tomaszg7** [comment] 2017-11-18 13:16
Hi,

I use Brief tab pinned and each time I update the addon, the tab disappears and I have to reopen it, pin and reorder again. 

Subscribing doesn't  work for me. Clicking on the rss icon in the address bar briefly displays some window but I can't even see its contents. When I point firefox directly to the rss feed's address and chose `Subscribe now` I get an error message: `File not found.
Firefox can’t find the file at chrome://brief/content/brief.xhtml?subscribe=http://tomaszg.pl/foto/rss.xml.`

Moreover Brief seems sluggish, especially on feeds with 100+ items. Sometimes you have to wait before anything is displayed or before an item is marked as read.

**Comment by Agglutinator** [comment] 2017-11-18 13:29
Brief version a5 worked for me but after updating to b1 all feeds were empty
Only when i subscribe to a completely new feed i never used before I can see feeds
Even deleting brief and deleting all data in my profile folder and then reinstall brief does not work.

Like i said - new feeds do work but somehow it killed all previously existing feeds irreversible

**Comment by tanriol** [comment] 2017-11-18 13:45
> I use Brief tab pinned and each time I update the addon, the tab disappears and I have to reopen it, pin and reorder again.

The same for me, Firefox closes the Brief tab. Sorry, no easy fix.

> Moreover Brief seems sluggish, especially on feeds with 100+ items. Sometimes you have to wait before anything is displayed or before an item is marked as read.

There are some performance problems that I need to deal with, but they don't block the 2.5.0 release.

> When I point firefox directly to the rss feed's address...

By any chance, is this a feed from `addons.mozilla.org`? Subscribing won't work with these.

If not, please check the debug console or the browser console for error messages.

**Comment by tanriol** [comment] 2017-11-18 13:46
@Agglutinator Please check whether 2.5.0b1 fixes this.

**Comment by miforefox** [comment] 2017-11-18 13:55
@tanriol Version 2.5.0b2 fixed everything and now brief works perfectly!

Thank you very much!

**Comment by eberhardweber** [comment] 2017-11-18 14:04
Deleting the Brief contents of \storage\permanent\ and of \browser-extension-data\brief@mozdev.org\ does not clear the Brief subscription database. What's the easiest way of completely wiping my Brief subscriptions/data? I deleted everything manually in the interface once after the above failed to clear the data for a new import test but won't be doing it again :D

**Comment by tomaszg7** [comment] 2017-11-18 14:18
> By any chance, is this a feed from addons.mozilla.org? Subscribing won't work with these.
No, it was my own feed at my webpage. And for some reason I cannot reproduce it anymore when I open the console. All I saw that might have been related was `An old Brief option selected for subscribing, intercepting`.

Anyway, lack of any reaction makes it impossible to say if feed was successfully subscribed, or e.g. there was some error or it was already subscribed.

> There are some performance problems that I need to deal with, but they don't block the 2.5.0 release.
Sure thing. It would be just good to see some visual indication that the work is being done, not that e.g. the feed is empty.

**Comment by eberhardweber** [comment] 2017-11-18 14:52
Also wondering if it is currently intended that the feeds are reordered after importing. I have a specific order the feeds were exported, and after a while, Brief reorders them on some premise!

**Comment by will76** [comment] 2017-11-18 16:07
Every time Brief refreshes the feeds it makes some items unread, even I already marked them as read!

**Comment by saffroy** [comment] 2017-11-18 16:37
First, thank you for porting your add-on to FF57! I am a SageRSS refugee, upgrading to 57 was a no-go until I found a suitable replacement, and Brief seems to fit the bill.

Migrating was not straightforward though. After several back & forths between versions (of Brief and FF), this is how I migrated:

1. under FF 56, export feeds from Sage as OPML
2. install Brief 2.4
3. import OPML: the order is reversed!
4. export OPML from Brief again
5. remove Brief
6. clean up bookmarks added by Brief when I imported
7. reinstall Brief 2.4
8. import OPML from second export: order is back to normal
9. upgrade FF from 56 to 57
10. install Brief 2.5b2

Whew!

**Comment by Agglutinator** [comment] 2017-11-18 18:09
Didn't fix it.
Even with b2 there is still the issue if you unsubscribe from a feed and subscribe again
it will stay empty. There is no way to reverse that.
Also weird, you can't completely delete brief. Even if you remove all visible storage data
and reinstall it, it will remember what feeds you previously subscribed to.

**Comment by tanriol** [comment] 2017-11-18 19:22
> Even with b2 there is still the issue if you unsubscribe from a feed and subscribe again
it will stay empty. There is no way to reverse that.

Hmm, I can't reproduce this, for me the items reappear correctly.

> Also weird, you can't completely delete brief. Even if you remove all visible storage data
and reinstall it, it will remember what feeds you previously subscribed to.

Brief stores a copy of the feed list into `storage.sync` for possible feed list synchronization and as a fallback (for me, "the user uninstalled Brief, installed it back and lost his feed list forever" seems to be a worse problem). This copy is stored, along with other extensions' data, somewhere in the profile and on the Firefox Sync servers if you have an account.

**Comment by Agglutinator** [comment] 2017-11-18 21:03
strange, i had my feeds which showed up as empty in brief and didn't do anything.
Now i checked again after some hours and they finally showed up.

Maybe this whole issue is just when you installed a1-> a2 -> ... -> a5 -> b1 -> b2

**Comment by stromfeldt** [comment] 2017-11-18 21:05
First off, thanks very much for your work on Brief! Of the two dozen or so add-ons I'm using it's the only one I ultimately couldn't do without and so has been holding me back from updating to 57 (not a complaint, just an indication of the importance of Brief to my usage of Firefox, and again my appreciation of your work).

If you don't mind I've got a bit of a mundane question for you (or anybody else). I've got Brief 2.4 installed on Firefox 56. I've also got a few hundred unread posts from various feeds, sometimes 50 or so unread posts from feeds that were I to refresh them from scratch would only grab the latest dozen or so posts (or whatever the default their RSS feeds are set at). As I'd like to keep those unread posts, will I be able to do so via updating to 2.5 (stable), because if I'm not mistaken exporting to an OPML file will only export the links for all the feeds, not the actual listing of posts.

Worst case scenario I could of course just open all those unread posts and bookmark them conventionally in Firefox before doing the udpate/migration.

Thanks again!

**Comment by tanriol** [comment] 2017-11-19 00:12
@Agglutinator Thank you for the reports! I've managed to isolate the "empty feeds after re-addition" problem and it turned out to be a bug in the query builder.

**Comment by tanriol** [comment] 2017-11-19 01:00
Released v2.5.0b3 with a few more fixes.

**Comment by Keith94** [comment] 2017-11-19 06:31
Importing feeds is still broken for me in my main profile (but works in a clean profile). FWIW I get this error.
>Error: can't access lexical declaration `feedID' before initialization  undefined

**Comment by rui-nibau** [comment] 2017-11-19 09:23
Hi Denis.

Just to say a HUGE HUGE THANK YOU for your work on Brief and porting it to web extension.

Migration done very simply:
* Exported my feeds as opml with brief and firefox esr.
* Imported in firefox 57 with 2.5.0b2.

The last tiny annoyance, collapsed folders that stay expanded each time i re-open Brief, is fixed in 2.5.0b3 :-D. 

Again, BIG THANK YOU.

**Comment by tanriol** [comment] 2017-11-19 09:54
@Keith94 
> Importing feeds is still broken for me in my main profile (but works in a clean profile).

For the same OPML file? Hm, I've tried to look at the corresponding code again and could not find the problem. Do I understand correctly that there's no file name and line number for that error?

**Comment by Keith94** [comment] 2017-11-19 09:57
>Do I understand correctly that there's no file name and line number for that error?

Correct, just the `undefined` at the end. And yes for the same OPML file.

**Comment by eberhardweber** [comment] 2017-11-19 13:44
I'd like to request a full Brief wipe button - at the very least for the duration of the beta. 

The behaviours I'm getting on my Brief b3 are impossible to test because of the rapid release cycle and various other reasons, the chief being that I have cruft between feed list imports.

Right now, I'm having some of my feeds import from the opml backup, some won't; some feeds will update, and some won't ever update at all. Updating some of them seems to take days. 

Unfortunately, I can't tell what the reason is, which beta is to blame, unless I can wipe :) If you think the delete button should go after the beta ends, that's fine, but right now, I think it would be really useful.

**Comment by mrror** [comment] 2017-11-19 15:41
Same problems with feeds visualization here with a3 (first I installed for Firefox 57). I tried cleaning up as much as I could: bookmarks (from Manage), bookmarks backups subfolder in profile folder, the old brief.sqlite, places.sqlite, Brief's storage.js but nothing helped. Both importing opml than manually readding feeds makes Brief react differently and inconsistently to each of (most won't load any items, some do but don't update, etc.). Maybe a fill Brief wipe is a good idea.

**Comment by fichtennadel** [comment] 2017-11-19 18:08
Two minor issues:

- clicking on the brief toolbar icon will open another instance instead of switching to the existing one.
- subscribe button shows empty list right here on this page (https://github.com/ancestorak/brief/issues/276) and adds feed immediately when clicked

**Comment by 92Julian** [comment] 2017-11-19 19:46
Feed Settings opens a blank window, I'm can't disable mark as unread changed items.

**Comment by PatrickS143** [comment] 2017-11-19 20:01
Thanks for making this available for ff57 so fast!
Strange thing here now. Version a1 till b2 were working fine for me. Today with b3 suddenly i have empty feeds, but when I looked in the trash there were all kinds of new items! items from 1 hour till a few hours ago. They apparently were all moved to trash automatically...
Some new setting I'm not aware of?

**Comment by etm** [comment] 2017-11-19 20:02
Brief: opening database in persistent storage - database.js:43:9
UnknownError - database.js:48:21

Works on 2 other machines though.

**Comment by tanriol** [comment] 2017-11-19 20:13
@92Julian Linux? I don't know what's going on but it sometimes shows blank until you resize it.

@PatrickS143 There are such settings, please check in options and/or feed settings the max entry count limit and max entry age. They should be disabled by default, IIRC.

@etm Never seen this before. Any non-standard configuration / privacy settings? You aren't running Brief in a browser configured to "Never save history", are you?

**Comment by PatrickS143** [comment] 2017-11-19 20:19
@tanriol All those settings are the same as I had before...
Items to be removed after 14 days and keep maximum of 100 items for each feed. So they should not go into trash immediately.

**Comment by etm** [comment] 2017-11-19 20:20
nope. custom settings.

Creating a new profile didn't do the trick. 
DELETING the whole .mozilla directory and starting fresh, did the trick though. Well, i guess my very old profile was somehow broken. Sync to the rescue, so not a problem.

Thanks for investing your valuable spare time. We appreciate it A LOT. Brief is fantastic.

**Comment by tanriol** [comment] 2017-11-19 20:21
@fichtennadel 
The first one is non-obvious - for example, I sometimes use several Brief tabs at once. If you have arguments for or against, please mention them in #277.

Showing the list of one item doesn't make much sense. However, Brief should provide some indication that it acted on your click and subscribed you to the feed.

**Comment by mrror** [comment] 2017-11-19 21:16
I ended up doing a Firefox refresh, uninstalling old Brief (installed from Sync), installing B3 and importing my OPML, now everything seems to work.

**Comment by 92Julian** [comment] 2017-11-19 21:38
> sometimes shows blank until you resize it.
Thanks, that works.

Why not use a popup inside Brief tab instead of a new window?

**Comment by tanriol** [comment] 2017-11-19 22:59
@92Julian Because I want to release 2.5.0 ASAP and don't want to delay it on significant changes.

BTW, this is really a [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1408446).

**Comment by tanriol** [comment] 2017-11-19 23:45
@PatrickS143 Thanks for reporting all entries being dropped, it was a nontrivial bug.

**Comment by tanriol** [comment] 2017-11-20 00:26
Released Beta 4. I hope this is the final one. Fixed entries expiration, added folder creating and renaming to the organize mode.

**Comment by mrror** [comment] 2017-11-20 00:54
All items in some feeds suddenly disappeared and didn't reappear when I tried to update :( (in b3, same when updated to b4)

**Comment by grigi** [comment] 2017-11-20 07:38
Same here, it seemsto be related to PatrickS143's issue. I cleared the expiriy settings, even reset the store, but nothing comes back?

**Comment by tanriol** [comment] 2017-11-20 08:17
They do not come back automatically as I can't distinguish between expired entries and the ones deleted manually. You can restore everything by opening the Brief tab, opening console with F12 and pasting/executing the following:
```javascript
Database.query({deleted: 'trashed'}).markDeleted(0)
```

**Comment by tanriol** [comment] 2017-11-20 08:18
Actually, you can just right-click Trash and "restore all items" :-)

**Comment by jnachtigall** [comment] 2017-11-20 08:30
First, a big thank you for the WE version <3 
(btw, there's no donate button at https://addons.mozilla.org/en-US/firefox/addon/brief/ like for other plugins, otherwise I'd be happy to at least send you some 15€ or so although it would pay in any way for the huge amount of work)

Using Nightly, I upgraded today to `Version 2.5.0b4`. I had 2.3 installed previously, I do not know why I was not upgraded to 2.4 in between, probably because I used Nightly and the 2.3 => 2.4 upgrade automatism was earlier broken for me than for stable users. Ok, I'll re-add my feeds manually, it's just a dozen or so...

Anyway after upgrading and restart, there's another permission window:
![2017-11-20 09_20_12-brief - nightly](https://user-images.githubusercontent.com/3307404/33008847-108a941c-cdd5-11e7-874c-ff0b8e24e0c3.png)

I do not know if this is a Firefox or Brief bug, but I guess it should say `Would you allow Brief...` instead of `Would you allow <some-cryptic-numer>...`

**Comment by dbenzhuser** [comment] 2017-11-20 09:21
+1 for the donate button.

Btw, the add-on page in Firefox still points to http://brief.mozdev.org/ as Brief's homepage. This page seems to be very outdated and still offers Brief 2.0 as a direct download (last change log entry is from march 2015).

I updated through 2.4 to 2.5a2 and now to 2.5b4 and have not encountered any issues. Great work!

**Comment by ilativ** [comment] 2017-11-20 10:31
Tanriol thanks for you work on Brief.

The current Beta work fine but I see this errors/warnings in the console:
```
11:25:48.208 Use of xml:base attribute is deprecated and will be removed soon. Please remove any use of it. feedview.js:961:8
11:26:15.726 TypeError: this.getEntryView(...) is undefined [Learn More] feedview.js:501:28
```

**Comment by mrror** [comment] 2017-11-20 10:39
+1 for the donate button

**Comment by will76** [comment] 2017-11-20 12:06
Is it just me or every time Brief refreshes the feeds it loads the same entries even if I had already marked them as read? It's pretty annoying.

**Comment by tanriol** [comment] 2017-11-20 13:01
@will76 It may be either a bad feed or a Brief bug (or both). If you share a link to some feed with this problem, I'll be able to tell you more.

**Comment by tanriol** [comment] 2017-11-20 14:30
I've submitted Brief 2.5.0 for review, so I'm closing this thread now. If there are any bugs or feature requests I've missed, you're welcome to comment on old issues if there are any or create new ones.

**Closed by tanriol** 2017-11-20 14:30 UTC
