### ISSUE TITLE
disable shortcut

### ISSUE THREAD

**Issue by ghost** [ancestorak/brief#234] opened 2017-04-04 15:04 UTC
in some language they're collisions with `local` keyboard char typing

**Comment by tanriol** [comment] 2017-04-04 15:33
Could you please provide an example of a bad shortcut and a situation where it stops you from typing? I don't understand this problem because most shortcuts are used in the Brief tab only and should not fire if you're working with a text input field.

**Comment by tanriol** [comment] 2017-11-20 15:17
Closing as never confirmed.

**Closed by tanriol** 2017-11-20 15:17 UTC
Labels: A-ui, S-unconfirmed, T-bug
