### ISSUE TITLE
Stopped working after today's (10/09/2015) firefox nightly update.

### ISSUE THREAD

**Issue by joder666** [ancestorak/brief#160] opened 2015-10-09 19:45 UTC
The title says it all. I already tried re-installing it on a clean profile and turning to false "xpinstall.signatures.required". No go.

Not sure if it is a Brief issue or Firefox's, since the later is going through its internal "transformation", so better to let you guys know.

**Comment by tanriol** [comment] 2015-10-09 19:50
Could you please describe what exactly does not work?
Also, do you have e10s (multi-process) enabled?

**Comment by tanriol** [comment] 2015-10-09 19:54
Confirming this, the Brief button, Options menu item and some other functionality stop working with `ReferenceError: Brief is not defined`.

**Comment by joder666** [comment] 2015-10-09 19:56
Sorry for my bad report....
I already tried with e10s on and off, forgot to mention it.

**Comment by tanriol** [comment] 2015-10-09 19:57
No problems, thank you for the report. Unfortunately, not sure I have enough time in the next two weeks to find it, but this is certainly to be fixed.

**Comment by joder666** [comment] 2015-10-09 20:02
Well if it can be fixed, take your time, i don't mind using "stable" (40) firefox on which Brief works OK.  I was more afraid of it stop working for good due to internal Firefox changes.
All other similar addons out there i either don't like or worse, have problems with recent version of Firefox.

**Comment by tanriol** [comment] 2015-10-09 20:12
This bug was not present in Nightly 2015-10-07, but already present in 2015-10-08.

**Comment by tanriol** [comment] 2015-10-09 20:55
Bisected with mozregression to [one patch series](https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=d6059530b0317e6f6b141582b611469505256be4&tochange=cfc1820361f599c55128b29de4332f8d06511e07)

**Comment by tanriol** [comment] 2015-10-20 16:04
Fixed with dfbebd8ba3a (not marked automatically due to a typo).

**Closed by tanriol** 2015-10-20 16:04 UTC
Labels: bug, P1, regression
