### ISSUE TITLE
Letters are not displayed correctly.

### ISSUE THREAD

**Issue by codenameUsernameisalreadytaken** [ancestorak/brief#225] opened 2017-02-04 09:56 UTC
Letters are not displayed correctly.

![1](https://cloud.githubusercontent.com/assets/25467998/22617549/a46167ec-eafa-11e6-8800-4e9233fa212f.JPG)

http://www.opennet.ru/opennews/opennews_all_noadv.rss

**Comment by tanriol** [comment] 2017-02-04 11:29
Cannot reproduce (works for me). Additional details (Brief version, Firefox version, OS) are welcome.

**Comment by tanriol** [comment] 2017-03-25 22:17
Closing as never confirmed. Feel free to reopen if you have any additional information.

**Closed by tanriol** 2017-03-25 22:17 UTC
Labels: unconfirmed
